CREATE TABLE `form_assessment_cmh` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `encounter` bigint(20) DEFAULT NULL,
  `dcn` varchar(10) DEFAULT NULL,
  `location` varchar(20) DEFAULT NULL,
  `time_start` varchar(10) DEFAULT NULL,
  `time_end` varchar(10) DEFAULT NULL,
  `referral_source` varchar(15) DEFAULT NULL,
  `new_client_eval` varchar(3) NOT NULL DEFAULT 'N/A',
  `readmission` varchar(3) NOT NULL DEFAULT 'N/A',
  `consultation` varchar(3) NOT NULL DEFAULT 'N/A',
  `copy_sent_to` varchar(25) DEFAULT NULL,
  `reason_why` longtext,
  `provider` varchar(30) DEFAULT NULL,
  `note_type` varchar(50) DEFAULT NULL,
  `units` varchar(10) NOT NULL,
  `service_code` varchar(10) DEFAULT NULL,
  `complaint` longtext,
  `background_history` longtext,
  `mh_history` longtext,
  `fam_mh_history` longtext,
  `sa_history` longtext,
  `fam_sa_history` longtext,
  `phys_history` longtext,
  `dev_history` longtext,
  `abuse_history` longtext,
  `violent_history` longtext,
  `education_history` longtext,
  `empl_history` longtext,
  `legal_history` longtext,
  `school_work` longtext,
  `personal_relationships` longtext,
  `fatherc` varchar(3) NOT NULL DEFAULT 'N/A',
  `motherc` varchar(3) NOT NULL DEFAULT 'N/A',
  `father_involved` longtext,
  `mother_involved` longtext,
  `number_children` tinyint(4) DEFAULT NULL,
  `siblings` longtext,
  `other_relationships` longtext,
  `social_relationships` longtext,
  `current_symptoms` longtext,
  `personal_strengths` longtext,
  `spiritual` varchar(15) DEFAULT NULL,
  `legal` varchar(20) DEFAULT NULL,
  `summary_justification` longtext,
  `axis1` longtext,
  `axis2` longtext,
  `axis3` longtext,
  `allergies` varchar(20) DEFAULT NULL,
  `ax4_prob_support_group` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_prob_soc_env` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_educational_prob` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_occ_prob` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_housing` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_economic` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_access_hc` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_legal` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_other_cb` varchar(3) NOT NULL DEFAULT 'N/A',
  `ax4_other` longtext,
  `ax5_current` varchar(3) DEFAULT NULL,
  `ax5_past` varchar(3) DEFAULT NULL,
  `risk_suicide_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_nk` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_io` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_plan` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_iwom` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_iwm` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_suicide_none` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_nk` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_io` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_plan` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_iwom` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_iwm` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_homocide_none` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_fc` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_mc` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_moc` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_var` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_compliance_no` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_substance_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_substance_none` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_normal_use` longtext,
  `risk_substance_ou` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_substance_dp` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_substance_ur` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_substance_ab` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_y` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_n` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_ry` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_rn` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_cv` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_cp` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_b` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_sexual_nf` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_na` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_y` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_n` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_ry` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_rn` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_cv` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_cp` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_cb` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_neglect_cn` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_exists_c` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_exists_cn` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_exists_s` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_exists_o` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_exists_b` varchar(3) NOT NULL DEFAULT 'N/A',
  `risk_community` longtext,
  `desired_services` longtext,
  `recommendations_psy_p` varchar(3) NOT NULL DEFAULT 'N/A',
  `recommendations_psy_i` varchar(3) NOT NULL DEFAULT 'N/A',
  `recommendations_psy_tboss` varchar(3) NOT NULL DEFAULT 'N/A',
  `recommendations_psy_d` varchar(3) NOT NULL DEFAULT 'N/A',
  `recommendations_psy_o` varchar(3) NOT NULL DEFAULT 'N/A',
  `recommendations_psy_notes` longtext,
  `refer_date` date DEFAULT NULL,
  `parent` date DEFAULT NULL,
  `referrals_pepm` longtext,
  `referrals_mc` longtext,
  `referrals_vt` longtext,
  `referrals_o` longtext,
  `referrals_cu` longtext,
  `referrals_docs` longtext,
  `referrals_or` longtext,
  `provider_print_name` varchar(30) DEFAULT NULL,
  `provider_signature` varchar(4000) DEFAULT NULL,
  `provider_credentials` varchar(20) DEFAULT NULL,
  `provider_signature_date` date DEFAULT NULL,
  `supervisor_print_name` varchar(30) DEFAULT NULL,
  `supervisor_signature` varchar(4000) DEFAULT NULL,
  `supervisor_credentials` varchar(20) DEFAULT NULL,
  `supervisor_signature_date` date DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'In Progress',
  `billing_status` varchar(30) NOT NULL DEFAULT 'Not Billed',
  `billing_id` bigint(20) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
