CREATE TABLE `form_progress_note` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT '0',
  `v_client_name` varchar(50) DEFAULT NULL,
  `v_pid` varchar(20) DEFAULT NULL,
  `v_encounter` varchar(20) DEFAULT NULL,
  `v_dos` date DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `tp_form_id` varchar(100) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT '0',
  `activity` tinyint(4) DEFAULT '0',
  `encounter` bigint(20) DEFAULT NULL,
  `note_type` varchar(10) DEFAULT NULL,
  `service_name` varchar(45) DEFAULT NULL,
  `service_code` varchar(45) DEFAULT NULL,
  `time_start` varchar(10) DEFAULT NULL,
  `time_end` varchar(10) DEFAULT NULL,
  `units` varchar(10) DEFAULT NULL,
  `diagnosis1` varchar(255) DEFAULT NULL,
  `diagnosis2` varchar(255) DEFAULT NULL,
  `diagnosis3` varchar(255) DEFAULT NULL,
  `diagnosis4` varchar(255) DEFAULT NULL,
  `problem` text,
  `goal` text,
  `subjective` text,
  `objective` text,
  `assessment` text,
  `plan` text,
  `deficit_problems_behavior_addressed` text,
  `interventions` text,
  `response_to_intervention` text,
  `status` varchar(45) DEFAULT NULL,
  `comments_log` longblob,
  `provider_print_name` varchar(30) DEFAULT NULL,
  `provider_signature` varchar(4000) DEFAULT NULL,
  `provider_credentials` varchar(20) DEFAULT NULL,
  `provider_signature_date` date DEFAULT NULL,
  `supervisor_print_name` varchar(30) DEFAULT NULL,
  `supervisor_signature` varchar(4000) DEFAULT NULL,
  `supervisor_credentials` varchar(20) DEFAULT NULL,
  `supervisor_signature_date` date DEFAULT NULL,
  `billing_status` varchar(30) DEFAULT 'Not Billed',
  `billing_id` bigint(20) DEFAULT '0',
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
