--
-- Table structure for table `form_treatment_plan`
--

CREATE TABLE IF NOT EXISTS `form_treatment_plan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT '0',
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT '0',
  `activity` tinyint(4) DEFAULT '0',
  `unit` tinyint(4) DEFAULT '1',
  `service_code` varchar(10) DEFAULT NULL,
  `service_name` varchar(45) DEFAULT NULL,
  `modality_note` varchar(255) DEFAULT '0',
  `approach_note` varchar(255) DEFAULT '0',
  `status` varchar(45) DEFAULT NULL,
  `comments_log` longblob,
  `provider_print_name` varchar(45) DEFAULT NULL,
  `provider_signature` varchar(4000) DEFAULT NULL,
  `provider_credentials` varchar(20) DEFAULT NULL,
  `provider_signature_date` date DEFAULT NULL,
  `supervisor_print_name` varchar(40) DEFAULT NULL,
  `supervisor_signature` varchar(4000) DEFAULT NULL,
  `supervisor_credentials` varchar(20) DEFAULT NULL,
  `supervisor_signature_date` date DEFAULT NULL,
  `physician_print_name` varchar(40) DEFAULT NULL,
  `physician_signature` varchar(4000) DEFAULT NULL,
  `physician_credentials` varchar(20) DEFAULT NULL,
  `physician_signature_date` date DEFAULT NULL,
  `patient_print_name` varchar(40) DEFAULT NULL,
  `patient_signature` varchar(4000) DEFAULT NULL,
  `patient_signature_date` date DEFAULT NULL,
  `guardian_print_name` varchar(40) DEFAULT NULL,
  `guardian_signature` varchar(4000) DEFAULT NULL,
  `guardian_signature_date` date DEFAULT NULL,
  `provider` varchar(45) DEFAULT NULL,
  `signatures_on_file` varchar(3) DEFAULT NULL,
  `encounter` bigint(20) DEFAULT NULL,
  `billing_status` varchar(30) DEFAULT 'Not Billed',
  `billing_id` bigint(20) DEFAULT NULL,
  `form_status` varchar(45) DEFAULT 'In Progress',
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
