CREATE TABLE `form_cfars` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT '0',
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT '0',
  `activity` tinyint(4) DEFAULT '0',
  `encounter` bigint(20) DEFAULT NULL,
  `units` varchar(10) NOT NULL DEFAULT '1',
  `service_code` varchar(10) DEFAULT 'H0031',
  `service_name` varchar(6) NOT NULL,
  `dcf_outcomes_report` varchar(65) DEFAULT NULL,
  `program_evaluation` varchar(65) DEFAULT NULL,
  `primary_diagnosis` varchar(10) DEFAULT NULL,
  `secondary_diagnosis` varchar(10) DEFAULT NULL,
  `substance_abuse_history` varchar(4) DEFAULT NULL,
  `cfars_rater_notes` varchar(255) DEFAULT NULL,
  `depression` tinyint(4) DEFAULT NULL,
  `depression_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `depression_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety` tinyint(4) DEFAULT NULL,
  `anxiety_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `anxiety_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity` tinyint(4) DEFAULT NULL,
  `hyperactivity_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyperactivity_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect` tinyint(4) DEFAULT NULL,
  `hyper_affect_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `hyper_affect_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process` tinyint(4) DEFAULT NULL,
  `thought_process_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `thought_process_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance` tinyint(4) DEFAULT NULL,
  `cognitive_performance_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `cognitive_performance_13` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical` tinyint(4) DEFAULT NULL,
  `medical_physical_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `medical_physical_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress` tinyint(4) DEFAULT NULL,
  `traumatic_stress_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `traumatic_stress_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use` tinyint(4) DEFAULT NULL,
  `substance_use_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `substance_use_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships` tinyint(4) DEFAULT NULL,
  `interpersonal_relationships_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `interpersonal_relationships_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting` tinyint(4) DEFAULT NULL,
  `behavior_in_home_setting_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `behavior_in_home_setting_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships` tinyint(4) DEFAULT NULL,
  `family_relationships_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_relationships_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment` tinyint(4) DEFAULT NULL,
  `family_environment_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `family_environment_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning` tinyint(4) DEFAULT NULL,
  `adl_functioning_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `adl_functioning_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal` tinyint(4) DEFAULT NULL,
  `socio_legal_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `socio_legal_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school` tinyint(4) DEFAULT NULL,
  `work_or_school_option` varchar(6) NOT NULL DEFAULT 'N/A',
  `work_or_school_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_13` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_14` varchar(3) NOT NULL DEFAULT 'N/A',
  `work_or_school_15` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self` tinyint(4) DEFAULT NULL,
  `ability_to_care_for_self_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `ability_to_care_for_self_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self` tinyint(4) DEFAULT NULL,
  `danger_to_self_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_self_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others` tinyint(4) DEFAULT NULL,
  `danger_to_others_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `danger_to_others_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs` tinyint(4) DEFAULT NULL,
  `security_management_needs_1` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_2` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_3` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_4` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_5` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_6` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_7` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_8` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_9` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_10` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_11` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_12` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_13` varchar(3) NOT NULL DEFAULT 'N/A',
  `security_management_needs_14` varchar(3) NOT NULL DEFAULT 'N/A',
  `provider_print_name` varchar(40) DEFAULT NULL,
  `provider` varchar(30) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'In Progress',
  `billing_status` varchar(30) NOT NULL DEFAULT 'Not Billed',
  `billing_id` bigint(20) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;